name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Recomendado pelo Sonar

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Altere se necessário

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests and generate coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
